### ISSUE TITLE
update go-ipfs

### ISSUE THREAD

**Issue by nothingismagick** [josselinchevalay/telescope#27]
go-ipfs v 0.4.10 is currently listed on the readme...

**Comment by josselinchevalay** [comment]
hi, 

yes currently, we need to install locally go-ipfs. We need to try that : https://github.com/ipfs/notes/issues/256 maybe. 

Regards

**Comment by josselinchevalay** [comment]
Currently i have this issue : 
̀
Error: version mismatch: expected v6, found v5
`

i will try to process to solve that
